#Menus
menu.tema
menu.idioma

#Temas
tema.oscuro
tema.claro

#Idiomas
idioma.espanol
idioma.ingles

#Titulos
informacion.puerto
informacion.eeprom
informacion.consola
programar.esp8266
progreso
extras

#Botones
eeprom.leer
eeprom.escribir
consola.info
consola.diagrama
programar.esp8266

#Etiquetas
extras.web