#Menus
menu.tema=Tema
menu.idioma=Idioma

#Temas
tema.oscuro=Tema oscuro
tema.claro=Tema claro

#Idiomas
idioma.espanol=Espa\u00f1ol
idioma.ingles=English

#Titulos
informacion.puerto=Puerto
informacion.eeprom=Eeprom
informacion.consola=Consola
programar.esp8266=Esp8266
progreso=Progreso
extras=Extras

#Botones
eeprom.leer=Leer eeprom
eeprom.escribir=Escribir eeprom
consola.info=Abrir LiveInfo
consola.diagrama=Mostrar diagrama
programar.esp8266=Programar esp8266

#Etiquetas
extras.web=Visita nuestro sitio web