#Menus
menu.tema=Theme
menu.idioma=Language

#Temas
tema.oscuro=Dark theme
tema.claro=White theme

#Idiomas
idioma.espanol=Espa\u00f1ol
idioma.ingles=English

#Titulos
informacion.puerto=Port
informacion.eeprom=Eeprom
informacion.consola=Console
programar.esp8266=Esp8266
progreso=Progress
extras=Extras

#Botones
eeprom.leer=Read eeprom
eeprom.escribir=Write eeprom
consola.info=Open LiveInfo
consola.diagrama=show diagram
programar.esp8266=Write esp8266

#Etiquetas
puerto.com=COM port:
extras.web=Visit our web site