package gui;

import logica.Tema;

/**
 * Esta clase es la interfaz gráfica del programa
 * @author Emmanuelito18
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiqueta = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        tema = new javax.swing.JMenu();
        temaOscuro = new javax.swing.JMenuItem();
        temaClaro = new javax.swing.JMenuItem();
        eeprom = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etiqueta.setText("Probador");

        tema.setText("menu.tema");

        temaOscuro.setText("tema.oscuro");
        temaOscuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temaOscuroActionPerformed(evt);
            }
        });
        tema.add(temaOscuro);

        temaClaro.setText("tema.claro");
        temaClaro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temaClaroActionPerformed(evt);
            }
        });
        tema.add(temaClaro);

        barraMenu.add(tema);

        eeprom.setText("menu.eeprom");

        jMenuItem1.setText("eeprom.leer");
        eeprom.add(jMenuItem1);

        jMenuItem2.setText("eeprom.escribir");
        eeprom.add(jMenuItem2);

        barraMenu.add(eeprom);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(etiqueta)
                .addContainerGap(196, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(etiqueta)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    Tema temaNuevo=new Tema();
    private void temaOscuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temaOscuroActionPerformed
       temaNuevo.actualizaTemaOscuro(this);
    }//GEN-LAST:event_temaOscuroActionPerformed

    private void temaClaroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temaClaroActionPerformed
        temaNuevo.actualizarTemaClaro(this);
    }//GEN-LAST:event_temaClaroActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenu eeprom;
    private javax.swing.JLabel etiqueta;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu tema;
    private javax.swing.JMenuItem temaClaro;
    private javax.swing.JMenuItem temaOscuro;
    // End of variables declaration//GEN-END:variables
}
